In [1]:
import pandas as pd
import numpy as np

### 집계 연산(Aggregation)

In [2]:
df = pd.DataFrame([[1, 1.2, np.nan],
                   [2.4, 5.5, 4.2,],
                   [np.nan, np.nan, np.nan],
                   [0.44, -3.1, -4.1]],
                   index=[1, 2, 3, 4],
                  columns=['A', 'B', 'C'])
df

A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [3]:
df.head(2)

A    B    C
1  1.0  1.2  NaN
2  2.4  5.5  4.2

In [4]:
df.tail(2)

A    B    C
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [5]:
df.describe()

A     B         C
count  3.000000  3.00  2.000000
mean   1.280000  1.20  0.050000
std    1.009554  4.30  5.868986
min    0.440000 -3.10 -4.100000
25%    0.720000 -0.95 -2.025000
50%    1.000000  1.20  0.050000
75%    1.700000  3.35  2.125000
max    2.400000  5.50  4.200000

In [12]:
print(df)
print(df.idxmin())
print(df.idxmax())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    4
B    4
C    4
dtype: int64
A    2
B    2
C    2
dtype: int64


In [13]:
print(df)
print(df.std())
print(df.var())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.009554
B    4.300000
C    5.868986
dtype: float64
A     1.0192
B    18.4900
C    34.4450
dtype: float64


In [15]:
print(df)
print(df.skew())
print(df.kurt())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    1.15207
B    0.00000
C        NaN
dtype: float64
A   NaN
B   NaN
C   NaN
dtype: float64


In [16]:
print(df)
print(df.sum())
print(df.cumsum())    # 누적합

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A    3.84
B    3.60
C    0.10
dtype: float64
      A    B    C
1  1.00  1.2  NaN
2  3.40  6.7  4.2
3   NaN  NaN  NaN
4  3.84  3.6  0.1


In [17]:
print(df)
print(df.prod())
print(df.cumprod())    # 누적곱

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1
A     1.056
B   -20.460
C   -17.220
dtype: float64
       A      B      C
1  1.000   1.20    NaN
2  2.400   6.60   4.20
3    NaN    NaN    NaN
4  1.056 -20.46 -17.22


In [18]:
df.diff()    # 이전 행 값과의 차이

A    B   C
1  NaN  NaN NaN
2  1.4  4.3 NaN
3  NaN  NaN NaN
4  NaN  NaN NaN

In [19]:
df.quantile()    # default는 0.5

A    1.00
B    1.20
C    0.05
Name: 0.5, dtype: float64

In [20]:
df.pct_change()   # 변화율

A         B        C
1       NaN       NaN      NaN
2  1.400000  3.583333      NaN
3  0.000000  0.000000  0.00000
4 -0.816667 -1.563636 -1.97619

In [21]:
df.corr()

A         B    C
A  1.000000  0.970725  1.0
B  0.970725  1.000000  1.0
C  1.000000  1.000000  1.0

In [22]:
df.corrwith(df.B)    # B값 기준 상관계수 출력

A    0.970725
B    1.000000
C    1.000000
dtype: float64

In [23]:
df.cov()

A       B       C
A  1.0192   4.214   8.134
B  4.2140  18.490  35.690
C  8.1340  35.690  34.445

In [24]:
df['B'].unique()

array([ 1.2,  5.5,  nan, -3.1])

In [25]:
df['A'].value_counts()

0.44    1
2.40    1
1.00    1
Name: A, dtype: int64

### Groupby 연산

In [27]:
df = pd.DataFrame({'c1':['a', 'a', 'b', 'b', 'c', 'd', 'b'],
                   'c2':['A', 'B', 'B', 'A', 'D', 'C', 'C'],
                   'c3':np.random.randint(7),
                   'c4':np.random.random(7)})
df

c1 c2  c3        c4
0  a  A   4  0.269602
1  a  B   4  0.338743
2  b  B   4  0.229289
3  b  A   4  0.946666
4  c  D   4  0.597770
5  d  C   4  0.200535
6  b  C   4  0.890300

In [29]:
df.dtypes

c1     object
c2     object
c3      int64
c4    float64
dtype: object

In [30]:
df['c3'].groupby(df['c1'])    # groupby는 객체이므로 집계값을 주면 출력 가능

In [32]:
df['c3'].groupby(df['c1']).mean()

c1
a    4
b    4
c    4
d    4
Name: c3, dtype: int64

In [34]:
df['c4'].groupby(df['c2']).std()

c2
A    0.478756
B    0.077396
C    0.487737
D         NaN
Name: c4, dtype: float64

In [35]:
df['c4'].groupby([df['c1'], df['c2']]).mean()

c1  c2
a   A     0.269602
    B     0.338743
b   A     0.946666
    B     0.229289
    C     0.890300
c   D     0.597770
d   C     0.200535
Name: c4, dtype: float64

In [36]:
df['c4'].groupby([df['c1'], df['c2']]).mean().unstack()    # 데이터프레임 형태로 바꾸기

c2         A         B         C        D
c1                                       
a   0.269602  0.338743       NaN      NaN
b   0.946666  0.229289  0.890300      NaN
c        NaN       NaN       NaN  0.59777
d        NaN       NaN  0.200535      NaN

In [37]:
df.groupby('c1').mean()

c3        c4
c1              
a    4  0.304173
b    4  0.688752
c    4  0.597770
d    4  0.200535

In [38]:
df.groupby(['c1', 'c2']).mean()

c3        c4
c1 c2              
a  A    4  0.269602
   B    4  0.338743
b  A    4  0.946666
   B    4  0.229289
   C    4  0.890300
c  D    4  0.597770
d  C    4  0.200535

In [39]:
df.groupby(['c1', 'c2']).size()

c1  c2
a   A     1
    B     1
b   A     1
    B     1
    C     1
c   D     1
d   C     1
dtype: int64

In [40]:
for c1, group in df.groupby('c1'):
  print(c1)
  print(group) 

a
  c1 c2  c3        c4
0  a  A   4  0.269602
1  a  B   4  0.338743
b
  c1 c2  c3        c4
2  b  B   4  0.229289
3  b  A   4  0.946666
6  b  C   4  0.890300
c
  c1 c2  c3       c4
4  c  D   4  0.59777
d
  c1 c2  c3        c4
5  d  C   4  0.200535


In [41]:
for (c1, c2), group in df.groupby(['c1', 'c2']):
  print((c1, c2))
  print(group)

('a', 'A')
  c1 c2  c3        c4
0  a  A   4  0.269602
('a', 'B')
  c1 c2  c3        c4
1  a  B   4  0.338743
('b', 'A')
  c1 c2  c3        c4
3  b  A   4  0.946666
('b', 'B')
  c1 c2  c3        c4
2  b  B   4  0.229289
('b', 'C')
  c1 c2  c3      c4
6  b  C   4  0.8903
('c', 'D')
  c1 c2  c3       c4
4  c  D   4  0.59777
('d', 'C')
  c1 c2  c3        c4
5  d  C   4  0.200535


In [43]:
df.groupby(['c1', 'c2'])[['c4']].mean()

c4
c1 c2          
a  A   0.269602
   B   0.338743
b  A   0.946666
   B   0.229289
   C   0.890300
c  D   0.597770
d  C   0.200535

In [44]:
df.groupby('c1')['c3'].quantile()

c1
a    4.0
b    4.0
c    4.0
d    4.0
Name: c3, dtype: float64

In [45]:
df.groupby('c1')['c3'].count()

c1
a    2
b    3
c    1
d    1
Name: c3, dtype: int64

In [46]:
df.groupby('c1')['c4'].median()

c1
a    0.304173
b    0.890300
c    0.597770
d    0.200535
Name: c4, dtype: float64

In [47]:
df.groupby('c1')['c4'].std()

c1
a    0.048889
b    0.398903
c         NaN
d         NaN
Name: c4, dtype: float64

In [49]:
df.groupby(['c1', 'c2'])['c4'].agg(['mean', 'min', 'max'])

mean       min       max
c1 c2                              
a  A   0.269602  0.269602  0.269602
   B   0.338743  0.338743  0.338743
b  A   0.946666  0.946666  0.946666
   B   0.229289  0.229289  0.229289
   C   0.890300  0.890300  0.890300
c  D   0.597770  0.597770  0.597770
d  C   0.200535  0.200535  0.200535

In [50]:
df.groupby(['c1', 'c2'], as_index=False)['c4'].mean()

c1 c2        c4
0  a  A  0.269602
1  a  B  0.338743
2  b  A  0.946666
3  b  B  0.229289
4  b  C  0.890300
5  c  D  0.597770
6  d  C  0.200535

In [51]:
df.groupby(['c1', 'c2'], as_index=False)['c4'].agg(['mean', 'min', 'max'])    # agg 함수 사용하면 as_index=False 적용 안됨

mean       min       max
c1 c2                              
a  A   0.269602  0.269602  0.269602
   B   0.338743  0.338743  0.338743
b  A   0.946666  0.946666  0.946666
   B   0.229289  0.229289  0.229289
   C   0.890300  0.890300  0.890300
c  D   0.597770  0.597770  0.597770
d  C   0.200535  0.200535  0.200535

In [52]:
df.groupby(['c1', 'c2'], group_keys=False)['c4'].mean()

c1  c2
a   A     0.269602
    B     0.338743
b   A     0.946666
    B     0.229289
    C     0.890300
c   D     0.597770
d   C     0.200535
Name: c4, dtype: float64

In [53]:
def top(df, n=3, column='c1'):
  return df.sort_values(by=column)[-n:]

top(df, n=5)

c1 c2  c3        c4
2  b  B   4  0.229289
3  b  A   4  0.946666
6  b  C   4  0.890300
4  c  D   4  0.597770
5  d  C   4  0.200535

In [58]:
df.groupby('c1').apply(top)

c1 c2  c3        c4
c1                      
a  0  a  A   4  0.269602
   1  a  B   4  0.338743
b  2  b  B   4  0.229289
   3  b  A   4  0.946666
   6  b  C   4  0.890300
c  4  c  D   4  0.597770
d  5  d  C   4  0.200535

### 피벗테이블(Pivot Table)

In [60]:
df.pivot_table(['c3', 'c4'],
               index=['c1'],
               columns=['c2'])

c3                       c4                             
c2    A    B    C    D         A         B         C        D
c1                                                           
a   4.0  4.0  NaN  NaN  0.269602  0.338743       NaN      NaN
b   4.0  4.0  4.0  NaN  0.946666  0.229289  0.890300      NaN
c   NaN  NaN  NaN  4.0       NaN       NaN       NaN  0.59777
d   NaN  NaN  4.0  NaN       NaN       NaN  0.200535      NaN

In [62]:
df.pivot_table(['c3', 'c4'],
               index=['c1'],
               columns=['c2'],
               margins=True)    # 행별, 열별 집계값 같이 출력

c3                           c4                                       
c2     A    B    C    D All         A         B         C        D       All
c1                                                                          
a    4.0  4.0  NaN  NaN   4  0.269602  0.338743       NaN      NaN  0.304173
b    4.0  4.0  4.0  NaN   4  0.946666  0.229289  0.890300      NaN  0.688752
c    NaN  NaN  NaN  4.0   4       NaN       NaN       NaN  0.59777  0.597770
d    NaN  NaN  4.0  NaN   4       NaN       NaN  0.200535      NaN  0.200535
All  4.0  4.0  4.0  4.0   4  0.608134  0.284016  0.545418  0.59777  0.496129

In [63]:
df.pivot_table(['c3', 'c4'],
               index=['c1'],
               columns=['c2'],
               margins=True,
               aggfunc=sum)

c3                           c4                                       
c2     A    B    C    D All         A         B         C        D       All
c1                                                                          
a    4.0  4.0  NaN  NaN   8  0.269602  0.338743       NaN      NaN  0.608345
b    4.0  4.0  4.0  NaN  12  0.946666  0.229289  0.890300      NaN  2.066255
c    NaN  NaN  NaN  4.0   4       NaN       NaN       NaN  0.59777  0.597770
d    NaN  NaN  4.0  NaN   4       NaN       NaN  0.200535      NaN  0.200535
All  8.0  8.0  8.0  4.0  28  1.216268  0.568031  1.090836  0.59777  3.472905

In [64]:
df.pivot_table(['c3', 'c4'],
               index=['c1'],
               columns=['c2'],
               margins=True,
               aggfunc=sum,
               fill_value=0)

c3                     c4                                       
c2   A  B  C  D All         A         B         C        D       All
c1                                                                  
a    4  4  0  0   8  0.269602  0.338743  0.000000  0.00000  0.608345
b    4  4  4  0  12  0.946666  0.229289  0.890300  0.00000  2.066255
c    0  0  0  4   4  0.000000  0.000000  0.000000  0.59777  0.597770
d    0  0  4  0   4  0.000000  0.000000  0.200535  0.00000  0.200535
All  8  8  8  4  28  1.216268  0.568031  1.090836  0.59777  3.472905

In [65]:
pd.crosstab(df.c1, df.c2)

c2  A  B  C  D
c1            
a   1  1  0  0
b   1  1  1  0
c   0  0  0  1
d   0  0  1  0

In [67]:
pd.crosstab(df.c1, df.c2, values=df.c3, aggfunc=sum, margins=True)

c2     A    B    C    D  All
c1                          
a    4.0  4.0  NaN  NaN    8
b    4.0  4.0  4.0  NaN   12
c    NaN  NaN  NaN  4.0    4
d    NaN  NaN  4.0  NaN    4
All  8.0  8.0  8.0  4.0   28

### 범주형(Categorical) 데이터

In [68]:
s = pd.Series(['c1', 'c2', 'c1', 'c2', 'c1'] * 2)
s

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
dtype: object

In [70]:
pd.unique(s)

array(['c1', 'c2'], dtype=object)

In [71]:
pd.value_counts(s)

c1    6
c2    4
dtype: int64

In [72]:
code = pd.Series([0, 1, 0, 1, 0] * 2)
code

0    0
1    1
2    0
3    1
4    0
5    0
6    1
7    0
8    1
9    0
dtype: int64

In [73]:
d = pd.Series(['c1', 'c2'])
d

0    c1
1    c2
dtype: object

In [74]:
d.take(code)

0    c1
1    c2
0    c1
1    c2
0    c1
0    c1
1    c2
0    c1
1    c2
0    c1
dtype: object

In [75]:
df = pd.DataFrame({'id':np.arange(len(s)),
                   'c':s,
                   'v':np.random.randint(1000, 5000, size=len(s))})
df

id   c     v
0   0  c1  2050
1   1  c2  2750
2   2  c1  1965
3   3  c2  1687
4   4  c1  4291
5   5  c1  2066
6   6  c2  4844
7   7  c1  4102
8   8  c2  4178
9   9  c1  3330

In [76]:
c = df['c'].astype('category')
c

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
Name: c, dtype: category
Categories (2, object): ['c1', 'c2']

In [77]:
c.values

['c1', 'c2', 'c1', 'c2', 'c1', 'c1', 'c2', 'c1', 'c2', 'c1']
Categories (2, object): ['c1', 'c2']

In [78]:
c.values.categories

Index(['c1', 'c2'], dtype='object')

In [79]:
c.values.codes

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int8)

In [80]:
df['c'] = c
df.c

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
Name: c, dtype: category
Categories (2, object): ['c1', 'c2']

In [81]:
c = pd.Categorical(['c1', 'c2', 'c3', 'c1', 'c2'])
c

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1', 'c2', 'c3']

In [82]:
categories = ['c1', 'c2', 'c3']
codes = [0, 1, 2, 0, 1]
c = pd.Categorical.from_codes(codes, categories)
c

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1', 'c2', 'c3']

In [83]:
pd.Categorical.from_codes(codes, categories)
c

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1', 'c2', 'c3']

In [84]:
pd.Categorical.from_codes(codes, categories, ordered=True)

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1' < 'c2' < 'c3']

In [85]:
c.as_ordered()

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1' < 'c2' < 'c3']

In [86]:
c.codes

array([0, 1, 2, 0, 1], dtype=int8)

In [87]:
c.categories

Index(['c1', 'c2', 'c3'], dtype='object')

In [89]:
c = c.set_categories(['c1', 'c2', 'c3', 'c4', 'c5'])
c.categories

Index(['c1', 'c2', 'c3', 'c4', 'c5'], dtype='object')

In [90]:
c.value_counts()

c1    2
c2    2
c3    1
c4    0
c5    0
dtype: int64

In [91]:
c[c.isin(['c1', 'c3'])]

['c1', 'c3', 'c1']
Categories (5, object): ['c1', 'c2', 'c3', 'c4', 'c5']

In [92]:
c = c.remove_unused_categories()    # 사용되지 않은 카테고리 삭제

In [93]:
c.categories

Index(['c1', 'c2', 'c3'], dtype='object')