In [2]:
import pandas as pd
import numpy as np

In [3]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)
np.save('a', a2)

[[7 6 6 2 3]
 [1 9 7 6 6]
 [5 5 5 8 4]
 [9 3 4 3 8]
 [4 5 5 1 2]]


In [4]:
!ls

a.npy  sample_data


In [5]:
b2 = np.random.randint(1, 10, size=(5, 5))
print(b2)
np.savez('ab', a2, b2)

[[6 4 8 6 3]
 [7 2 5 3 2]
 [1 8 7 5 8]
 [3 2 9 5 6]
 [4 1 2 1 7]]


In [6]:
!ls

ab.npz	a.npy  sample_data


In [7]:
npy = np.load('a.npy')
print(npy)

[[7 6 6 2 3]
 [1 9 7 6 6]
 [5 5 5 8 4]
 [9 3 4 3 8]
 [4 5 5 1 2]]


In [9]:
npz = np.load('ab.npz')
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[7 6 6 2 3]
 [1 9 7 6 6]
 [5 5 5 8 4]
 [9 3 4 3 8]
 [4 5 5 1 2]]
[[6 4 8 6 3]
 [7 2 5 3 2]
 [1 8 7 5 8]
 [3 2 9 5 6]
 [4 1 2 1 7]]


In [10]:
print(a2)
np.savetxt('a.csv', a2, delimiter=',')    # 사람이 읽을 수 있는 text 형태로 저장

[[7 6 6 2 3]
 [1 9 7 6 6]
 [5 5 5 8 4]
 [9 3 4 3 8]
 [4 5 5 1 2]]


In [11]:
!ls

ab.npz	a.csv  a.npy  sample_data


In [12]:
!cat a.csv    # text로 저장해서 데이터 형태는 반영안되고 실수 형태로 출력됨. binary는 데이터 형태 저장 가능

7.000000000000000000e+00,6.000000000000000000e+00,6.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
1.000000000000000000e+00,9.000000000000000000e+00,7.000000000000000000e+00,6.000000000000000000e+00,6.000000000000000000e+00
5.000000000000000000e+00,5.000000000000000000e+00,5.000000000000000000e+00,8.000000000000000000e+00,4.000000000000000000e+00
9.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00,3.000000000000000000e+00,8.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,5.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00


In [13]:
csv = np.loadtxt('a.csv', delimiter=',')
print(csv)

[[7. 6. 6. 2. 3.]
 [1. 9. 7. 6. 6.]
 [5. 5. 5. 8. 4.]
 [9. 3. 4. 3. 8.]
 [4. 5. 5. 1. 2.]]


In [14]:
print(b2)
np.savetxt('b.csv', b2, delimiter=',', fmt='%.2e', header='c1, c2, c3, c4, c5')

[[6 4 8 6 3]
 [7 2 5 3 2]
 [1 8 7 5 8]
 [3 2 9 5 6]
 [4 1 2 1 7]]


In [15]:
!cat b.csv

# c1, c2, c3, c4, c5
6.00e+00,4.00e+00,8.00e+00,6.00e+00,3.00e+00
7.00e+00,2.00e+00,5.00e+00,3.00e+00,2.00e+00
1.00e+00,8.00e+00,7.00e+00,5.00e+00,8.00e+00
3.00e+00,2.00e+00,9.00e+00,5.00e+00,6.00e+00
4.00e+00,1.00e+00,2.00e+00,1.00e+00,7.00e+00


In [16]:
csv = np.loadtxt('b.csv', delimiter=',')
print(csv)

[[6. 4. 8. 6. 3.]
 [7. 2. 5. 3. 2.]
 [1. 8. 7. 5. 8.]
 [3. 2. 9. 5. 6.]
 [4. 1. 2. 1. 7.]]
